# Generated by Django 4.2.11 on 2024-04-26 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('movie_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('number_of_seats', models.IntegerField()),
                ('time_from', models.IntegerField()),
                ('time_to', models.IntegerField()),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SeatPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rows', models.IntegerField()),
                ('side', models.IntegerField()),
                ('movie_name', models.CharField(max_length=255)),
                ('is_included', models.BooleanField(default=False)),
                ('preference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.moviepreferences')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGoer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
