# Generated by Django 4.2.11 on 2024-04-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_seatpreferences_movie_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviepreferences',
            old_name='user_id',
            new_name='user',
        ),
    ]
