# Generated by Django 4.2.11 on 2024-04-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_user_id_moviepreferences_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatpreferences',
            old_name='preference_id',
            new_name='preference',
        ),
        migrations.AlterField(
            model_name='moviepreferences',
            name='date',
            field=models.DateField(),
        ),
    ]
